#version 450

layout(push_constant) uniform parameter {
    uint IW; uint IH; uint C; uint N;
    uint OW; uint OH; uint WG; uint HG;
    uint elements;
} p;
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) readonly buffer X { float input_data[]; };
layout(binding = 1) writeonly buffer D { float output_data[]; };

void main() {
    const uint x_span = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
    const uint y_span = gl_NumWorkGroups.y * gl_WorkGroupSize.y;
    const uint idx = gl_GlobalInvocationID.x + x_span *
        (gl_GlobalInvocationID.y + y_span * gl_GlobalInvocationID.z);
    if (idx >= p.elements) return;
    uint q = idx;
    const uint ox = q % p.OW; q /= p.OW;
    const uint oy = q % p.OH; q /= p.OH;
    const uint gx = q % p.WG; q /= p.WG;
    const uint gy = q % p.HG; q /= p.HG;
    const uint c = q % p.C;
    const uint n = q / p.C;
    const uint ix = gx * p.OW + ox;
    const uint iy = gy * p.OH + oy;
    output_data[idx] = input_data[ix + p.IW * (iy + p.IH * (c + p.C * n))];
}
